# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/movie-rec',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/movie-rec',
                'lib_path': 'movie_rec'},
  'syms': { 'movie_rec.core': {'movie_rec.core.foo': ('core.html#foo', 'movie_rec/core.py')},
            'movie_rec.movie_recommender': { 'movie_rec.movie_recommender.get_movie_recs': ( 'movie_recommender.html#get_movie_recs',
                                                                                             'movie_rec/movie_recommender.py'),
                                             'movie_rec.movie_recommender.search_movies_n_recommend': ( 'movie_recommender.html#search_movies_n_recommend',
                                                                                                        'movie_rec/movie_recommender.py')}}}