# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/movie-rec',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/movie-rec',
                'lib_path': 'movie_rec'},
  'syms': {'movie_rec.core': {'movie_rec.core.foo': ('core.html#foo', 'movie_rec/core.py')}}}